spring.application.name=Skillio_CRM
spring.datasource.url=jdbc:mysql://localhost:3306/Skillio_db?createDatabaseIfNotExist=true&useSSL=false&serverTimeZone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Jayesh@2711

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

app.jwt-secret=QWlyV2ViQ0xJUXMxMmM0NTZjNzg5MTIzNDU2Nzg5MTAxMjM0NQ==
app.jwt-expiration-milliseconds=86400000


#logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

# Set Hibernate SQL logging to WARN or ERROR to reduce trace/debug logs
spring.main.banner-mode=off
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR
